name: eof_podcast_feed
version: 1.1.0
description: eof_podcast_feed is a package for Dart and Flutter that Read and Parse RSS Feed
homepage: https://github.com/luizeof/dart-eof-podcast-feed
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  xml: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5
